#!/bin/bash

# This script is executed every time a theme is applied.
# Each generator can have it's own mondo-apply script.

# The default syntax is bash, but by changing the shebang,
# one could use another language (f.i. perl or python).

# $1 is equal to: $MONOD_DIR/generator/TYPE/THEME[.extensions]

# If this script is not needed, this file can safely be removed.
# (removing the file, will improve execution speed)

# this_dir="${1%/*}"
# this_file="${1##*/}"
# this_theme="${this_file%.*}"

# To source the settings file one could use this:
# source "${this_dir}/mondo-settings"

