#!/bin/bash

main(){

  declare -A keys
  mode=launch

  while getopts :e option; do
    case "${option}" in
      e ) mode=edit ;;
    esac
  done

  parsconfig

  displaymenu "$mode"
}

parsconfig(){
  eval "$(i3-msg -t get_config | awk '
  BEGIN {foundkeys=0}
  {

    if($1=="mode") {ismode=1}
    if($1=="}")    {ismode=0}

    gsub(/["]/,"\\\"",$0)

    original=$0

    for(k in variables){
      gsub("[$]"k,variables[k],$0)
    }

    if($1=="bindsym" && ismode!=1){

      gsub("[$]","\\$",original)

      if($0!~"exec"){msg="i3-msg "}
      else {msg=""}

      gsub(/bindsym|--release|exec|--no-startup-id/,"",$0)
      
      gsub("+","",$1)

      sub("Mod4","#",$1)
      sub("Mod1","!",$1)
      sub("Control","^",$1)
      sub("Shift","+",$1)

      bindsym=$1
      $1=""
      sub(/^[[:space:]]*/,"",$0)
      cmd=$0
      realcmd=msg cmd

      print "keys[" foundkeys "-bindsym]=\"" bindsym "\""
      print "keys[" foundkeys "-cmd]=\"" cmd "\""
      print "keys[" foundkeys "-realcmd]=\"" realcmd "\""
      print "keys[" foundkeys "-original]=\"" original "\""

      foundkeys++
    }

    #  $super bindsym Mod4
    if($1=="set"){
      sub("[$]","",$2)
      uservar=$2
      $1=$2=""
      sub(/^[[:space:]]*/,"",$0)
      userval=$0
      variables[uservar]=userval
    }
    
  }

  END {
    print "foundkeys=" foundkeys
  }

  ')"
}

displaymenu(){

  mode="$1"

  [[ $mode = edit ]] \
    && promptstring="edit line: " \
    || promptstring="launch command: "

  selected="$({
    for ((i=0;i<foundkeys;i++)); do
      printf '<span background="#222222" foreground="#eeeeee">%s</span> %s\n' \
             "${keys[${i}-bindsym]}" "${keys[${i}-cmd]}"
    done
  } | rofi -dmenu -format i -markup-rows -p "$promptstring")"

  [[ -z $selected ]] && exit 1

  case $mode in
    edit )
      oldline="${keys[${selected}-original]}"
      newline="$(rofi -dmenu -filter "$oldline" -theme-str '#entry {width: 100%;}')"
    
      [[ -z $newline ]] && exit 1

      i3configfile="$(i3 --moreversion | awk '$1=="Loaded"{print $4;exit}')"

      i3-msg -t get_config | awk -v ol="$oldline" -v nl="$newline" '
                             {if(ol==$0) print nl; else print $0} 
                             ' > "$i3configfile"

      i3-msg reload
    ;;

    launch ) echo "${keys[${selected}-realcmd]}" ;;
  esac

  
}

main "${@}"
