#!/bin/bash

# Terminate already running bar instances
killall -q polybar

listpid=$(getpid "i3listen.py")

[[ -n $listpid ]] && kill "$listpid"

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# polybar example &
polybar example -r > /dev/null 2>&1 &

# start listener
i3listen.py > /dev/null 2>&1 &
