#!/bin/bash

# This script is executed AFTER all other applying
# actions and scripts are finished, when mondo is 
# executed with the apply option (-a).

# The intension of this script is to let you adjust
# your environment after applying a new theme.

# For instance one might want to reload certain processes
# like windowmanagers and statusbars. 

# reload urxvt
kill -1 $(pidof urxvtd)
gtkrc-reload


polybarstart

i3-msg restart

